query {
  searchCatalogs(input: { text: "slack", limit: 25 }) {
    catalogs {
      integrationName
      description
      formConfigs {
        passportName
        type
        formItems {
          name
          type
          isPlaintext
          options {
            name
          }
        }
      }
      promptEmailTemplateId
      promptAVendorEmailAddress
      isPromptAVendorCompatible
      dataPointsCustomizable
      allowedActions
    }
  }
}
